Limit Checks to Syntax Errors

diff --git a/dev_scripts/hooks/pre-commit b/dev_scripts/hooks/pre-commit
--- a/dev_scripts/hooks/pre-commit
+++ b/dev_scripts/hooks/pre-commit
@@ -46,52 +46,52 @@ if [ "$PHP_FILES" != "" ]; then
 fi
 
 # Check if PHP-CS-FIXER is set up correctly
-if [ ! -x $PHP_FIX_BIN ]; then
-	echo ""
-	echo ""
-	echo "PHP-CS-FIXER not Found or not Executable ... Aborting"
-	echo ""
-	exit 1
-else
-	# Check if PHPCBF is set up correctly
-	if [ ! -x $PHP_CBF_BIN ]; then
-		echo ""
-		echo ""
-   		echo "PHPCBF not Found or not Executable ... Aborting"
-		echo ""
-		exit 1
-	else
-		# Execute PHPCBF & PHP-CS-FIXER
-		echo ""
-		echo ""
-		echo "Fixing Coding Style ..."
-		echo ""
-		for TARGET_FILE in $ALL_FILES
-		do
-			# Unstage target file
-			RET=$(git reset HEAD $PROJECT/$TARGET_FILE)
-
-			# Apply coding style to target file
-			RET=$($PHP_CBF_BIN --standard=$PHP_CBF_CONFIG_START $PROJECT/$TARGET_FILE)
-			RET=$($PHP_FIX_BIN fix --config "$PHP_FIX_CONFIG" $PROJECT/$TARGET_FILE)
-			RET=$($PHP_CBF_BIN --standard=$PHP_CBF_CONFIG_END $PROJECT/$TARGET_FILE)
-
-			# Stage target file
-			git add $PROJECT/$TARGET_FILE
-		done
-
-		# Check for changes staged but not committed
-		RET=$(git diff --cached)
-
-		if [ "$RET" == "" ]; then
-			echo "NOTE: Commit Emptied After Style Fix ... Aborting"
-			echo ""
-			exit 1
-		fi
-
-		# Completed
-		echo ""
-		echo "Coding Style Fixed"
-		echo ""
-	fi
-fi
+#if [ ! -x $PHP_FIX_BIN ]; then
+#	echo ""
+#	echo ""
+#	echo "PHP-CS-FIXER not Found or not Executable ... Aborting"
+#	echo ""
+#	exit 1
+#else
+#	# Check if PHPCBF is set up correctly
+#	if [ ! -x $PHP_CBF_BIN ]; then
+#		echo ""
+#		echo ""
+#  		echo "PHPCBF not Found or not Executable ... Aborting"
+#		echo ""
+#		exit 1
+#	else
+#		# Execute PHPCBF & PHP-CS-FIXER
+#		echo ""
+#		echo ""
+#		echo "Fixing Coding Style ..."
+#		echo ""
+#		for TARGET_FILE in $ALL_FILES
+#		do
+#			# Unstage target file
+#			RET=$(git reset HEAD $PROJECT/$TARGET_FILE)
+#
+#			# Apply coding style to target file
+#			RET=$($PHP_CBF_BIN --standard=$PHP_CBF_CONFIG_START $PROJECT/$TARGET_FILE)
+#			RET=$($PHP_FIX_BIN fix --config "$PHP_FIX_CONFIG" $PROJECT/$TARGET_FILE)
+#			RET=$($PHP_CBF_BIN --standard=$PHP_CBF_CONFIG_END $PROJECT/$TARGET_FILE)
+#
+#			# Stage target file
+#			git add $PROJECT/$TARGET_FILE
+#		done
+#
+#		# Check for changes staged but not committed
+#		RET=$(git diff --cached)
+#
+#		if [ "$RET" == "" ]; then
+#			echo "NOTE: Commit Emptied After Style Fix ... Aborting"
+#			echo ""
+#			exit 1
+#		fi
+#
+#		# Completed
+#		echo ""
+#		echo "Coding Style Fixed"
+#		echo ""
+#	fi
+#fi
